/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author MenyongMenying
 */
public class frameBuatAkun_2 extends javax.swing.JFrame {

  /**
   * Creates new form frameBuatAkun_2
   */
  Date date = new Date();
  SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
  
  public String nama;
  public String username;
  public String tanggal = format.format(date);
  
  public frameBuatAkun_2() {
    initComponents();
  }
  
  public void buatAkun(String nama, String username,String password, String tanggal){
    kode.Koneksi koneksi = new kode.Koneksi();
    Statement st;
    ResultSet rs;
    String query;
    
    query = "INSERT INTO user(nama, username, password, tanggal_dibuat) VALUES ('"+nama+"','"+username+"','"+password+"','"+tanggal+"')";
    
    try{
      st = koneksi.koneksi().createStatement();
      int hasil = st.executeUpdate(query);
      
      if(hasil > 0){
        query = "SELECT * FROM user WHERE username = '"+username+"'";
        
        try{
          st = koneksi.koneksi().createStatement();
          rs = st.executeQuery(query);
          if(rs.next()){
            frameHome frameHome = new frameHome(rs.getString("id_user"));
            
            JOptionPane.showMessageDialog(null, "Berhasil menambahkan user");
            frameHome.setVisible(true);

          }
        } catch(SQLException e){
          System.out.println(e.getMessage());
        }
        
      } else{
        JOptionPane.showMessageDialog(null, "Gagal menambahkan user");
      }
      
    } catch(SQLException e){
      System.out.println(e.getMessage());
    }
  
  }
  
  public void f_button_submit(String password, String konfirmasiPassword){
//    JOptionPane.showMessageDialog(null, this.nama+this.username+password);

    if(password.equals("")){
      JOptionPane.showMessageDialog(null, "Password Wajib Diisi");
    } else{
        if(password.equals(konfirmasiPassword)){
//          JOptionPane.showMessageDialog(null, this.nama+this.username+password+this.tanggal);
            this.buatAkun(this.nama, this.username, password, this.tanggal);
        } else{
          JOptionPane.showMessageDialog(null, "password tidak sama");
        }
    }
      
  }
  
  public void f_button_login(){
    frameLogin frameLogin = new frameLogin();
    frameLogin.setVisible(true);
    
    dispose();
  }

  /**
   * This method is called from within
   * the constructor to initialize the
   * form. WARNING: Do NOT modify this
   * code. The content of this method is
   * always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    input_password = new javax.swing.JTextField();
    button_submit = new javax.swing.JButton();
    button_login = new javax.swing.JButton();
    input_konfirmasiPassword = new javax.swing.JPasswordField();
    background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    input_password.setBackground(new java.awt.Color(0,0,0,0));
    input_password.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    input_password.setForeground(new java.awt.Color(100, 100, 100));
    input_password.setBorder(null);
    getContentPane().add(input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 160, 290, 30));

    button_submit.setBackground(new java.awt.Color(0,0,0,0));
    button_submit.setBorder(null);
    button_submit.setBorderPainted(false);
    button_submit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_submitActionPerformed(evt);
      }
    });
    getContentPane().add(button_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 340, 80, 32));

    button_login.setBackground(new java.awt.Color(0,0,0,0));
    button_login.setBorder(null);
    button_login.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_loginActionPerformed(evt);
      }
    });
    getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 180, 16));

    input_konfirmasiPassword.setBackground(new java.awt.Color(0,0,0,0));
    input_konfirmasiPassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    input_konfirmasiPassword.setForeground(new java.awt.Color(100, 100, 100));
    input_konfirmasiPassword.setBorder(null);
    getContentPane().add(input_konfirmasiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 240, 290, 30));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Sign-2.png"))); // NOI18N
    background.setToolTipText("");
    getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_submitActionPerformed
    // TODO add your handling code here:
    this.f_button_submit(input_password.getText(), input_konfirmasiPassword.getText());    
  }//GEN-LAST:event_button_submitActionPerformed

  private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
    // TODO add your handling code here:
    this.f_button_login();
  }//GEN-LAST:event_button_loginActionPerformed

  /**
   * @param args the command line
   * arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new frameBuatAkun_2().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JButton button_login;
  private javax.swing.JButton button_submit;
  private javax.swing.JPasswordField input_konfirmasiPassword;
  private javax.swing.JTextField input_password;
  // End of variables declaration//GEN-END:variables
}
