/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.TableColumn;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MenyongMenying
 */
public class frameProfil extends javax.swing.JFrame {

  /**
   * Creates new form frameProfil
   */
  kode.Koneksi koneksi = new kode.Koneksi();
  
  Statement st;
  ResultSet rs;
  
  public String id_user;
  public String nama;
  public String username;
  public String password;
  public String tanggalDibuat;
  public boolean cekUser;

  public frameProfil(String id_user) {
    initComponents();
    this.id_user = id_user;
    this.ambilData_dataUser(id_user);
    
    label_nama.setText(this.nama);
    label_username.setText(this.username);
    label_password.setText(this.password);
    label_tanggalDibuat.setText(this.tanggalDibuat);
    input_namaBaru.setText(this.nama);
    input_usernameBaru.setText(this.username);
    input_passwordBaru.setText(this.password);
  }
  
  public void ambilData_dataUser(String id_user){
    String query = "SELECT * FROM user WHERE id_user = '"+id_user+"'";
    
    try{
      st = koneksi.koneksi().createStatement();
      rs = st.executeQuery(query);
      
      if(rs.next()){
        this.nama = rs.getString("nama");
        this.username = rs.getString("username");
        this.password = rs.getString("password");
        this.tanggalDibuat = rs.getString("tanggal_dibuat");
      } else{
        this.nama = "";
        this.username = "";
        this.password = "";
        this.tanggalDibuat = "";
      }
      
    } catch(SQLException e){
      System.out.println(e.getMessage());
    }
    
  }
  
  public void f_button_submit(String nama, String username, String password){
    cekUser(username);
    if(this.cekUser == true){
      this.updateDataUser(nama, username, password);
      this.ambilData_dataUser(this.id_user);
      
      label_nama.setText(this.nama);
      label_username.setText(this.username);
      label_password.setText(this.password);
      label_tanggalDibuat.setText(this.tanggalDibuat);
      input_namaBaru.setText(this.nama);
      input_usernameBaru.setText(this.username);
      input_passwordBaru.setText(this.password);
    } else{
      JOptionPane.showMessageDialog(null, "Username telah digunakan pengguna lain");
       this.ambilData_dataUser(this.id_user);
      
      label_nama.setText(this.nama);
      label_username.setText(this.username);
      label_password.setText(this.password);
      label_tanggalDibuat.setText(this.tanggalDibuat);
      input_namaBaru.setText(this.nama);
      input_usernameBaru.setText(this.username);
      input_passwordBaru.setText(this.password);
    }
      
  }

  public void cekUser(String usernameBaru){
    String query = "SELECT * FROM user WHERE username = '"+usernameBaru+"' AND id_user != '"+this.id_user+"' ";
    try{
      st = koneksi.koneksi().createStatement();
      rs = st.executeQuery(query);
      
      if(rs.next()){
//        JOptionPane.showMessageDialog(null, "Usernaem telah digunakan oleh pengguna lain");
        this.cekUser = false;
      } else{
        this.cekUser = true;
      }
      
    } catch(SQLException e){
      System.out.println(e.getMessage());
    }
  }
  
  public void updateDataUser(String nama, String username, String password){
    String query = "UPDATE user SET nama = '"+nama+"', username = '"+username+"', password = '"+password+"' WHERE user.id_user = '"+this.id_user+"'";
    try{
      st = koneksi.koneksi().createStatement();
      int hasil = st.executeUpdate(query);
      
      if(hasil > 0){
        JOptionPane.showMessageDialog(null, "Berhasil mengupdate data");
      } else {
        JOptionPane.showMessageDialog(null, "Berhasil mengupdate data");
      }
      
    } catch(SQLException e){
      System.out.println(e.getMessage());
    }
  }
  
  /**
   * This method is called from within
   * the constructor to initialize the
   * form. WARNING: Do NOT modify this
   * code. The content of this method is
   * always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nav_home = new javax.swing.JButton();
    nav_pemasukanHariIni = new javax.swing.JButton();
    nav_pengeluaranHariIni = new javax.swing.JButton();
    nav_dataPemasukan = new javax.swing.JButton();
    nav_dataPengeluaran = new javax.swing.JButton();
    nav_profil = new javax.swing.JButton();
    nav_logout = new javax.swing.JButton();
    label_nama = new javax.swing.JLabel();
    label_username = new javax.swing.JLabel();
    label_password = new javax.swing.JLabel();
    label_tanggalDibuat = new javax.swing.JLabel();
    input_namaBaru = new javax.swing.JTextField();
    input_usernameBaru = new javax.swing.JTextField();
    input_passwordBaru = new javax.swing.JTextField();
    button_submit = new javax.swing.JButton();
    background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    nav_home.setBackground(new java.awt.Color(0,0,0,0));
    nav_home.setBorder(null);
    nav_home.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_homeActionPerformed(evt);
      }
    });
    getContentPane().add(nav_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 50));

    nav_pemasukanHariIni.setBackground(new java.awt.Color(0,0,0,0));
    nav_pemasukanHariIni.setBorder(null);
    nav_pemasukanHariIni.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_pemasukanHariIniActionPerformed(evt);
      }
    });
    getContentPane().add(nav_pemasukanHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

    nav_pengeluaranHariIni.setBackground(new java.awt.Color(0,0,0,0));
    nav_pengeluaranHariIni.setBorder(null);
    nav_pengeluaranHariIni.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_pengeluaranHariIniActionPerformed(evt);
      }
    });
    getContentPane().add(nav_pengeluaranHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

    nav_dataPemasukan.setBackground(new java.awt.Color(0,0,0,0));
    nav_dataPemasukan.setBorder(null);
    nav_dataPemasukan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_dataPemasukanActionPerformed(evt);
      }
    });
    getContentPane().add(nav_dataPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 50));

    nav_dataPengeluaran.setBackground(new java.awt.Color(0,0,0,0));
    nav_dataPengeluaran.setBorder(null);
    nav_dataPengeluaran.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_dataPengeluaranActionPerformed(evt);
      }
    });
    getContentPane().add(nav_dataPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 50));

    nav_profil.setBackground(new java.awt.Color(0,0,0,0));
    nav_profil.setBorder(null);
    nav_profil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_profilActionPerformed(evt);
      }
    });
    getContentPane().add(nav_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 50));

    nav_logout.setBackground(new java.awt.Color(0,0,0,0));
    nav_logout.setBorder(null);
    nav_logout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nav_logoutActionPerformed(evt);
      }
    });
    getContentPane().add(nav_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, 50));

    label_nama.setBackground(new java.awt.Color(0,0,0,0)
    );
    label_nama.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    label_nama.setForeground(new java.awt.Color(80, 80, 80));
    getContentPane().add(label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 192, 190, 26));

    label_username.setBackground(new java.awt.Color(0,0,0,0)
    );
    label_username.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    label_username.setForeground(new java.awt.Color(80, 80, 80));
    label_username.setToolTipText("");
    getContentPane().add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 229, 190, 26));

    label_password.setBackground(new java.awt.Color(0,0,0,0)
    );
    label_password.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    label_password.setForeground(new java.awt.Color(80, 80, 80));
    label_password.setToolTipText("");
    getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 266, 190, 26));

    label_tanggalDibuat.setBackground(new java.awt.Color(0,0,0,0)
    );
    label_tanggalDibuat.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    label_tanggalDibuat.setForeground(new java.awt.Color(80, 80, 80));
    label_tanggalDibuat.setToolTipText("");
    getContentPane().add(label_tanggalDibuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 302, 190, 26));

    input_namaBaru.setBackground(new java.awt.Color(0,0,0,0));
    input_namaBaru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    input_namaBaru.setForeground(new java.awt.Color(80, 80, 80));
    input_namaBaru.setBorder(null);
    getContentPane().add(input_namaBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 430, 190, 26));

    input_usernameBaru.setBackground(new java.awt.Color(0,0,0,0));
    input_usernameBaru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    input_usernameBaru.setForeground(new java.awt.Color(80, 80, 80));
    input_usernameBaru.setBorder(null);
    getContentPane().add(input_usernameBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 467, 190, 26));

    input_passwordBaru.setBackground(new java.awt.Color(0,0,0,0));
    input_passwordBaru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    input_passwordBaru.setForeground(new java.awt.Color(80, 80, 80));
    input_passwordBaru.setBorder(null);
    getContentPane().add(input_passwordBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 504, 190, 26));

    button_submit.setBackground(new java.awt.Color(0,0,0,0));
    button_submit.setForeground(new java.awt.Color(80, 80, 80));
    button_submit.setBorder(null);
    button_submit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_submitActionPerformed(evt);
      }
    });
    getContentPane().add(button_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 540, 198, 26));

    background.setBackground(new java.awt.Color(0,0,0,0));
    background.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profil.png"))); // NOI18N
    getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void nav_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_homeActionPerformed
    // TODO add your handling code here:
    frameHome frameHome = new frameHome(this.id_user);
    frameHome.setVisible(true);
    
    dispose();
  }//GEN-LAST:event_nav_homeActionPerformed

  private void nav_pemasukanHariIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_pemasukanHariIniActionPerformed
    // TODO add your handling code here:
    framePemasukanHariIni framePemasukanHariIni = new framePemasukanHariIni(this.id_user);
    framePemasukanHariIni.setVisible(true);
    dispose();
  }//GEN-LAST:event_nav_pemasukanHariIniActionPerformed

  private void nav_pengeluaranHariIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_pengeluaranHariIniActionPerformed
    // TODO add your handling code here:
    framePengeluaranHariIni framePengeluaranHariIni = new framePengeluaranHariIni(this.id_user);
    framePengeluaranHariIni.setVisible(true);

    dispose();
  }//GEN-LAST:event_nav_pengeluaranHariIniActionPerformed

  private void nav_dataPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_dataPemasukanActionPerformed
    // TODO add your handling code here:
    frameDataPemasukan frameDataPemasukan = new frameDataPemasukan(this.id_user);
    frameDataPemasukan.setVisible(true);

    dispose();
  }//GEN-LAST:event_nav_dataPemasukanActionPerformed

  private void nav_dataPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_dataPengeluaranActionPerformed
    // TODO add your handling code here:
    frameDataPengeluaran frameDataPengeluaran = new frameDataPengeluaran(this.id_user);
    frameDataPengeluaran.setVisible(true);

    dispose();
  }//GEN-LAST:event_nav_dataPengeluaranActionPerformed

  private void nav_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_profilActionPerformed
    // TODO add your handling code here:
    frameProfil frameProfil = new frameProfil(this.id_user);
    frameProfil.setVisible(true);

    dispose();
  }//GEN-LAST:event_nav_profilActionPerformed

  private void nav_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_logoutActionPerformed
    // TODO add your handling code here:
    dispose();
  }//GEN-LAST:event_nav_logoutActionPerformed

  private void button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_submitActionPerformed
    // TODO add your handling code here
    this.f_button_submit(input_namaBaru.getText(), input_usernameBaru.getText(), input_passwordBaru.getText());
  }//GEN-LAST:event_button_submitActionPerformed

  /**
   * @param args the command line
   * arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(frameProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(frameProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(frameProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(frameProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JButton button_submit;
  private javax.swing.JTextField input_namaBaru;
  private javax.swing.JTextField input_passwordBaru;
  private javax.swing.JTextField input_usernameBaru;
  private javax.swing.JLabel label_nama;
  private javax.swing.JLabel label_password;
  private javax.swing.JLabel label_tanggalDibuat;
  private javax.swing.JLabel label_username;
  private javax.swing.JButton nav_dataPemasukan;
  private javax.swing.JButton nav_dataPengeluaran;
  private javax.swing.JButton nav_home;
  private javax.swing.JButton nav_logout;
  private javax.swing.JButton nav_pemasukanHariIni;
  private javax.swing.JButton nav_pengeluaranHariIni;
  private javax.swing.JButton nav_profil;
  // End of variables declaration//GEN-END:variables
}
