/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author MenyongMenying
 */
public class frameBuatAkun_1 extends javax.swing.JFrame {

  /**
   * Creates new form frameBuatAkun_1
   */
  
  public frameBuatAkun_1() {
    initComponents();
  }
  
  public void f_button_submit(String nama, String username){
    kode.Koneksi koneksi = new kode.Koneksi();
    Statement st;
    ResultSet rs;
    String query;
    
    query = "SELECT * FROM user WHERE username = '"+username+"'";
    
    if(nama.equals("") || username.equals("")){
      JOptionPane.showMessageDialog(null, "Nama dan Username Wajib Diisi");
    } else{
        try {
        st = koneksi.koneksi().createStatement();
        rs = st.executeQuery(query);

        if(rs.next()){
          JOptionPane.showMessageDialog(null, "username telah digunakan oleh pengguna lain");
        } else {
          frameBuatAkun_2 frameBuatAkun_2 = new frameBuatAkun_2();
          frameBuatAkun_2.setVisible(true);
          frameBuatAkun_2.nama = nama;
          frameBuatAkun_2.username = username;

          dispose();
        } 

      } catch(SQLException e){
        System.out.println(e.getMessage());
      }
    }
  }

  public void f_button_login(){
    frameLogin frameLogin = new frameLogin();
    frameLogin.setVisible(true);
    
    dispose();
  }
  
  /**
   * This method is called from within
   * the constructor to initialize the
   * form. WARNING: Do NOT modify this
   * code. The content of this method is
   * always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    input_nama = new javax.swing.JTextField();
    input_username = new javax.swing.JTextField();
    button_submit = new javax.swing.JButton();
    button_login = new javax.swing.JButton();
    background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    input_nama.setBackground(new java.awt.Color(0,0,0,0));
    input_nama.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    input_nama.setForeground(new java.awt.Color(100, 100, 100));
    input_nama.setBorder(null);
    getContentPane().add(input_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 160, 290, 30));

    input_username.setBackground(new java.awt.Color(0,0,0,0));
    input_username.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    input_username.setForeground(new java.awt.Color(100, 100, 100));
    input_username.setBorder(null);
    getContentPane().add(input_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 240, 290, 30));

    button_submit.setBackground(new java.awt.Color(0,0,0,0));
    button_submit.setBorder(null);
    button_submit.setBorderPainted(false);
    button_submit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_submitActionPerformed(evt);
      }
    });
    getContentPane().add(button_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 340, 80, 32));

    button_login.setBackground(new java.awt.Color(0,0,0,0));
    button_login.setBorder(null);
    button_login.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_loginActionPerformed(evt);
      }
    });
    getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 180, 16));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Sign-1.png"))); // NOI18N
    background.setToolTipText("");
    getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_submitActionPerformed
    // TODO add your handling code here:
    this.f_button_submit(input_nama.getText(), input_username.getText());
  }//GEN-LAST:event_button_submitActionPerformed

  private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
    // TODO add your handling code here:
    this.f_button_login();
  }//GEN-LAST:event_button_loginActionPerformed

  /**
   * @param args the command line
   * arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(frameBuatAkun_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new frameBuatAkun_1().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JButton button_login;
  private javax.swing.JButton button_submit;
  private javax.swing.JTextField input_nama;
  private javax.swing.JTextField input_username;
  // End of variables declaration//GEN-END:variables
}
